name: elderly_care
description: A Flutter app for elderly care using AI

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.0
  cloud_firestore: ^3.1.0
  speech_to_text: ^5.0.0
  flutter_tts: ^3.2.0
  http: ^0.13.0
  url_launcher: ^6.0.0
  geolocator: ^8.0.0
  flutter_local_notifications: ^9.0.0
  tensorflow_lite_flutter: ^0.9.0  # For TensorFlow Lite integration

dev_dependencies:
  flutter_test:
    sdk: flutter